Added jetty's alpn-api dep for maven malfunction?
For some reason, server sent events sample is getting the error:
java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN .
The class is among dependencirs of org.eclipse.jetty/jetty-alpn-server,
which is listed in project.clj. For now, the artitact is added
not to require users to add this in their project.clj