io.pedestal.http.jetty: use SslContextFactory$Server
The plain org.eclipse.jetty.util.ssl.SslContextFactory has been
deprecated since Jetty 9.4.16.v20190411 and does not support some more
complicated SSL setups such as when SNI is required or when a
certificate contains multiple SAN with wildcard certificates:

  java.lang.IllegalStateException: KeyStores with multiple certificates
  are not supported on the base class
  org.eclipse.jetty.util.ssl.SslContextFactory. (Use
  org.eclipse.jetty.util.ssl.SslContextFactory$Server or
  org.eclipse.jetty.util.ssl.SslContextFactory$Client instead)

Since Jetty is being used as a HTTPS server, use the appropriate factory
for server SSL contexts instead.